# https://taskfile.dev

version: '3'

dotenv: ['.env', 'dev.env', '{{.USER_WORKING_DIR}}/dev.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  cogent:
    taskfile: ./cogent.taskfile.yml
    flatten: true

