# yaml-language-server: $schema=https://taskfile.dev/schema.json

# todo

version: '3'


# MUST have this ONLY in root for env variables to work.
dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  # Pick if you want local or remote task file loading.
  # https://taskfile.dev/usage/#flatten-includes makes it all the same either way.
  local: 
    taskfile: ./../../dev-taskfile.yml
    flatten: true
  #remote: 
  #  taskfile: https://raw.githubusercontent.com/joeblew999/pb-stack/refs/heads/main/dev-taskfile.yml
  #  flatten: true

vars:
  BASE_SRC_NAME: todo-with-task-includes

tasks:
  default:
    cmds:
      - task base
      - task base:tools
      - task go:bin