# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  remote: 
    taskfile: ./../../../../remote-taskfile.yml
    flatten: true

vars:
  # BUG: THIS SHOULD BE overriding !!
  GIT_VAR_SRC_REPO_URL: https://github.com/joeblew999/pb-stack-example
  GIT_VAR_SRC_REPO_NAME: pb-stack-example

tasks:
  default:
    cmds:
      - task git


