version: '3'

vars:
  UWD: '{{.USER_WORKING_DIR}}'
  FOLDER01_NAME: 'folder01'
  FOLDER01_PATH: '{{joinPath .USER_WORKING_DIR .FOLDER01_NAME}}'
  FOLDER02_NAME: "bar/foo"
  FOLDER02_PATH: '{{joinPath .UWD .FOLDER02_NAME}}'

tasks:
  default:
    cmds:
      - echo 'UWD:' {{.UWD}}
      - echo 'FOLDER01_NAME:' {{.FOLDER01_NAME}}
      - echo 'FOLDER01_PATH:' {{.FOLDER01_PATH}}
      - echo 'FOLDER02_NAME:' {{.FOLDER02_NAME}}
      - echo 'FOLDER02_PATH:' {{.FOLDER02_PATH}}
    silent: true