version: '3'

vars:
  FOO: '{{.USER_WORKING_DIR}}'
  BAR: "bar/foo"
  FUBAR: '{{joinPath .FOO .BAR}}'

tasks:
  default:
    cmds:
      - echo 'FOO:' {{.FOO}}
      - echo 'BAR:' {{.BAR}}
      - echo 'FUBAR:' {{joinPath .FOO .BAR}}
      - echo 'FUBAR:' {{.FUBAR}}              ***** NOT OK
      - echo '{{.FUBAR}}'                           ***** OK
      - echo '{{spew .FUBAR}}'                  ***** internally, OK
      - echo 'FUBAR:' test\\foo\bar          ***** here, the problem is generated directly
      - echo 'FUBAR:' {{shellQuote .FUBAR}} **** This will FIX the problem