# .task-experiments.yml
# If .env and .task-experiments.yml are present the values in the .task-experiments.yml file take precedence.

experiments:
  TASK_X_ENV_PRECEDENCE: 1
  TASK_X_GENTLE_FORCE: 1 
  TASK_X_MAP_VARIABLES: 2
  TASK_X_REMOTE_TASKFILES: 1
