# .task-experiments.yml
# If .env and .task-experiments.yml are present the values in the .task-experiments.yml file take precedence.

experiments:
  
  # https://taskfile.dev/experiments/env-precedence
  TASK_X_ENV_PRECEDENCE: 1

  # https://taskfile.dev/experiments/gentle-force/
  TASK_X_GENTLE_FORCE: 1

  # https://taskfile.dev/experiments/map-variables/?proposal=2
  TASK_X_MAP_VARIABLES: 2

  # https://taskfile.dev/experiments/remote-taskfiles/
  TASK_X_REMOTE_TASKFILES: 1