# .taskrc.yml

experiments:
  
  # https://taskfile.dev/experiments/env-precedence
  # Before this experiment, the OS variable took precedence over the task environment variable. This experiment changes the precedence to make the task environment variable take precedence over the OS variable.
  ENV_PRECEDENCE: 1

  # https://taskfile.dev/experiments/gentle-force/
  GENTLE_FORCE: 1

  # https://taskfile.dev/experiments/map-variables/?proposal=2
  #MAP_VARIABLES: 2

  # https://taskfile.dev/experiments/remote-taskfiles/
  REMOTE_TASKFILES: 1