
# https://taskfile.dev

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  # base for all
  base: ./base.taskfile.yml

  # task for devtime
  git: ./git.taskfile.yml
  go: ./go.taskfile.yml
  #vscode: ./vscode.taskfile.yml

  
  # task for runtime
  caddy: ./mod/caddy/taskfile.yml
  cloudflare: ./mod/cloudflare/taskfile.yml
  compose: ./mod/compose/taskfile.yml
  datastar: ./mod/datastar/taskfile.yml
  gh: ./mod/github/taskfile.yml
  kamal: ./mod/kamal/taskfile.yml
  minio: ./mod/minio/taskfile.yml
  pb: ./mod/pocketbase/taskfile.yml
  #reck: ./mod/reck/taskfile.yml
  remote:
    # binary needed: https://github.com/aquasecurity/trivy/releases/tag/v0.60.0
    # https://github.com/saydulaev/taskfile
    taskfile: https://raw.githubusercontent.com/saydulaev/taskfile/v1.4.3/Taskfile.yml
    

vars:
  #PB_GEN_BIN_VERSION: latest
  PB_GEN_BIN_VERSION: latest

tasks:
  default:
    desc: Welcome. 
    cmds:
      - echo ""
      #- task --list-all --yes --sort alphanumeric
      #- task --list-all --yes --sort alphanumeric
      - task --list-all --yes --sort none
      
      #- task --list-all --yes --sort alphanumeric --json
    silent: true
  bin:
    desc: build everything explicitly.
    cmds:
      - echo ""
      - echo "Building from root downwards ..."
      
      #- cd proj/todo-empty && task go:bin
      - cd proj/todo-with-all && task go:bin
      - cd proj/todo-with-task && task go:bin
      - cd proj/todo-with-task-includes && task go:bin
      - cd proj/todo-with-taskrc && task go:bin
    silent: true

