version: '3'

vars:
  APP_NAME: gui-robot
  BIN_DIR: .bin
  CMD_DIR: ./cmd/gui-robot

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - echo "GUI Robot - AI-Powered GUI Automation"
      - echo "Available tasks:"
      - task --list

  build:
    desc: "Build the application"
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/{{.APP_NAME}} {{.CMD_DIR}}

  test:
    desc: "Run tests"
    cmds:
      - go test -v ./...

  clean:
    desc: "Clean build artifacts"
    cmds:
      - rm -rf {{.BIN_DIR}}

  demo:
    desc: "Run demo"
    deps: [build]
    cmds:
      - echo "Running demo..."
      - ./{{.BIN_DIR}}/{{.APP_NAME}} -command get_screen_info

  screen-info:
    desc: "Get screen info"
    deps: [build]
    cmds:
      - ./{{.BIN_DIR}}/{{.APP_NAME}} -command get_screen_info
