

# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['.env', 'all.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  # base for all, with variables used for by most other includes.
  base:
    taskfile: ./base.taskfile.yml

  # task for devtime. Best to have them always loaded.
  git:				
    taskfile: ./git.taskfile.yml
  ci:     		
    taskfile: ./ci.taskfile.yml
  go:         
    taskfile: ./go.taskfile.yml
  #vscode: ./vscode.taskfile.yml

  
  # task for runtime.
  #caddy:      ./mod/caddy
  #cloudflare: ./mod/cloudflare
  #compose:    ./mod/compose
  #datastar: 	./mod/datastar
  #gh: 				./mod/github
  #kamal: 			./mod/kamal
  #minio: 			./mod/minio
  #pb: 				./mod/pocketbase
  #reck: ./mod/reck/taskfile.yml
  #remote:
    # binary needed: https://github.com/aquasecurity/trivy/releases/tag/v0.60.0
    # https://github.com/saydulaev/taskfile
    #taskfile: https://raw.githubusercontent.com/saydulaev/taskfile/v1.4.3/Taskfile.yml


tasks:
  default:
    desc: Welcome. 
    cmds:
      - echo ''
      #- task --list-all --yes --sort alphanumeric
      #- task --list-all --yes --sort alphanumeric
      #- task --list-all --yes --sort none

      - '{{.BASE_TASK_CMD}} --list-all --yes --sort none'
      
      #- task --list-all --yes --sort alphanumeric --json
    silent: false
  all:
    desc: build all explicitly.
    cmds:
      - echo ''
      - echo 'Building all ...'
      - echo 'get shell tools installed ...'
      - '{{.BASE_TASK_CMD}} go:bin'
      # mod
      - echo 'Build a Modules ...'
      #- cd mod/caddy && {{.BASE_TASK_CMD}} go:bin
      # proj
      - echo 'Build a Project or 2 ...'
      # works, but only with explicit calls, otherwise it self loops.
      - cd proj/todo-with-task-includes && {{.BASE_TASK_CMD}} bin
      # work, calling all. I guess because of "remote" at start of calls.
      - cd proj/todo-with-task-remote && {{.BASE_TASK_CMD}} all
    silent: false
