# yaml-language-server: $schema=https://taskfile.dev/schema.json

# taskfile.yml

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['.env', 'all.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  local: 
    taskfile: ./remote-taskfile.yml
    flatten: true
  #remote: 
  #  taskfile: https://raw.githubusercontent.com/joeblew999/pb-stack/refs/heads/main/remote-taskfile.yml
  #  flatten: true

  #remote:
  #   https://github.com/saydulaev/taskfile
  #   taskfile: https://raw.githubusercontent.com/saydulaev/taskfile/v1.4.3/Taskfile.yml
  #   flatten: true


tasks:
  default:
    desc: Welcome. 
    cmds:
      - '{{.BASE_TASK_CMD}} --list-all --yes --sort none --verbose'
    silent: false

  all:
    desc: all
    cmds:
      - echo ''
      - echo ' *** Building all ...'
      - echo ''

      # base
      - echo ''
      - echo ' *** test base is working ...'
      - '{{.BASE_TASK_CMD}} base:test'
      - echo ''

      # git
      - echo ''
      - echo '*** test git is working ...'
      - '{{.BASE_TASK_CMD}} git'
      - echo ''

      # go
      - echo ''
      - echo '*** test go is working ...'
      - '{{.BASE_TASK_CMD}} go'
      - echo ''

      # mod
      -  echo 'Build modules, that my projects need ...'
      - cd mod/_template/binary-local && {{.BASE_TASK_CMD}}
      - cd mod/_template/binary-remote && {{.BASE_TASK_CMD}}
      - cd mod/_template/source-local && {{.BASE_TASK_CMD}}
      - cd mod/_template/source-remote && {{.BASE_TASK_CMD}}
     
    
      # Operators projects
      - echo 'Build projects, that my Operators need ...'
      - cd proj/_template/binary-local && {{.BASE_TASK_CMD}}

      # Users Projects
      - echo 'Build projects, that my Users need ...'
      - echo 'These are all non '


     
    silent: false
