# yaml-language-server: $schema=https://taskfile.dev/schema.json

# taskfile.yml

version: '3'

vars:

  BASE_BINARY_EXTENSION: '{{if eq OS "windows"}}.exe{{end}}'

  THIS_SRC_NAME: gio-plugins
  THIS_SRC_PATH: '{{.THIS_SRC_NAME}}/webviewer/demo'
  THIS_BIN_NAME: 'demo{{.BASE_BINARY_EXTENSION}}'
  THIS_BIN_PATH: '{{.THIS_SRC_PATH}}/.bin/{{.THIS_BIN_NAME}}'

tasks:
  default:
    desc: Welcome. 
    cmds:
      - echo '{{.BASE_BINARY_EXTENSION}}'
      - echo '{{.THIS_SRC_NAME}}'
      - echo '{{.THIS_SRC_PATH}}'
      - echo '{{.THIS_BIN_NAME}}'
      - echo '{{.THIS_BIN_PATH}}'
    silent: true

  src:
    cmds:
      - task src:gio
      - task src:plugins
  src:gio:
    cmds:
      # gio cmd
      - git clone https://github.com/inkeliz/gio.git
      - echo gio >> .gitignore

  src:plugins:
    cmds:
      # plugins
      - git clone https://github.com/gioui-plugins/gio-plugins.git
      - echo {{.THIS_SRC_NAME}} >> .gitignore
  mod:work:
    cmds:
      - echo > go.work
      - go work use gio
      - go work use {{.THIS_SRC_PATH}}
  mod:upgrade:
    cmds:
      - cd {{.THIS_SRC_PATH}} && go mod tidy
      # https://github.com/marwan-at-work/mod
      # can migrate UP or Down...
      - go install github.com/marwan-at-work/mod/cmd/mod@latest
      - cd {{.THIS_SRC_PATH}} && mod upgrade -h
      - cd {{.THIS_SRC_PATH}} && go mod tidy
  mod:downgrade:
    cmds:
      - cd {{.THIS_SRC_PATH}} && go mod tidy
      # https://github.com/marwan-at-work/mod
      # can migrate UP or Down...
      - go install github.com/marwan-at-work/mod/cmd/mod@latest
      - cd {{.THIS_SRC_PATH}} && mod downgrade -h
      - cd {{.THIS_SRC_PATH}} && go mod tidy

  dev:
    cmds:
      - cd {{.THIS_SRC_PATH}} && go run .
  bin:
    cmds:
      - cd {{.THIS_SRC_PATH}} && go build -o .bin/{{.THIS_BIN_NAME}}
  run:
    cmds:
      - '{{.THIS_BIN_PATH}}'
  release:
    cmds:
      # send up so others can use it.
      - echo 'release'
