# yaml-language-server: $schema=https://taskfile.dev/schema.json

# taskfile.yml

version: '3'

vars:

  THIS_SRC_NAME: gio-plugins
  THIS_SRC_PATH: '{{.THIS_SRC_NAME}}/webviewer/demo'
  THIS_BIN_NAME: 'demo'
  THIS_BIN_PATH: '{{.THIS_SRC_PATH}}/.bin/{{.THIS_BIN_NAME}}/'

tasks:
  default:
    desc: Welcome. 
    cmds:
      - echo '{{.THIS_SRC_NAME}}'
      - echo '{{.THIS_SRC_PATH}}'
      - echo '{{.THIS_BIN_NAME}}'
      - echo '{{.THIS_BIN_PATH}}'
    silent: true

  src:
    cmds:
      - task src:gio
      - task src:plugins
  src:gio:
    cmds:
      # gio cmd
      - git clone https://github.com/inkeliz/gio.git
      - echo gio >> .gitignore

  src:plugins:
    cmds:
      # plugins
      - git clone https://github.com/gioui-plugins/gio-plugins.git
      - echo {{.THIS_SRC_NAME}} >> .gitignore
  mod:
    cmds:
      - echo > go.work
      - go work use gio
      - go work use {{.THIS_SRC_PATH}}
  dev:
    cmds:
      - cd {{.THIS_SRC_PATH}} && go run .
  bin:
    cmds:
      - cd {{.THIS_SRC_PATH}} && go build -o .bin/{{.THIS_BIN_NAME}}
  run:
    cmds:
      - .{{.THIS_BIN_PATH}} 
