# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['dev.env', '{{.ENV}}/.env', '{{.HOME}}/.env']


includes:
  dev: 
    taskfile: ./../../../dev-taskfile.yml
    flatten: true

vars:

  # https://github.com/nushell/nushell
  NU_BIN_NAME: 'nu{{.BASE_BINARY_EXTENSION}}'
  # https://github.com/nushell/nushell/releases/tag/0.104.0
  NU_BIN_VERSION: 0.104.0
  NU_BIN_WHICH: ''
  NU_BIN_WHICH_VERSION: ''

tasks:
  default:
    cmds:
      - echo ''
      - echo '- bin'
      - echo 'NU_BIN_NAME:'                 {{.NU_BIN_NAME}}
      - echo 'NU_BIN_VERSION:'              {{.NU_BIN_VERSION}}
      - echo 'NU_BIN_WHICH:'                
      - task dep:which
      - echo 'NU_BIN_WHICH_VERSION:'        {{.NU_BIN_WHICH_VERSION}}
      - echo ''
    silent: true

  os:
    desc: print the OS and ARCH, to check the shell is working.
    cmds:
      - cmd: echo 'on darwin/amd64'
        platforms: [darwin/amd64]
      - cmd: echo 'on darwin/arm64'
        platforms: [darwin/arm64]

      - cmd: echo 'on linux/amd64'
        platforms: [linux/amd64]
      - cmd: echo 'on linux/arm64'
        platforms: [linux/arm64]

      - cmd: echo 'on windows/amd64'
        platforms: [windows/amd64]
      - cmd: echo 'on windows/arm64'
        platforms: [windows/arm64]

      # exotics
      - cmd: echo 'on openbsd, dragonfly, freebsd, netbsd'
        platforms: [openbsd, dragonfly, freebsd, netbsd]


### dep

  dep:
    cmds:
      - echo ''
      - echo 'releaser install'
      #- '{{.GO_BIN_NAME}} install github.com/goreleaser/goreleaser/v2@{{.NU_BIN_VERSION}}'
      - echo ''
    silent: false
  dep:del:
    cmds:
      - rm -f {{.BASE_DEP_PATH}}/{{.NU_BIN_NAME}}
      - ls -al {{.BASE_DEP_PATH}}/{{.NU_BIN_NAME}}
  dep:which:
    cmds:
      - task base:shell-which -- {{.NU_BIN_NAME}}
  dep:which:version:
    cmds:
      - '{{.NU_BIN_NAME}} --version'

### install 

  install:
    cmds:
      - cmd: brew install nushell
        platforms: [darwin]
      - cmd: winget install nushell
        platforms: [windows]
  install:del:
    cmds:
      - cmd: brew uninstall nushell
        platforms: [darwin]
      - cmd: winget uninstall nushell
        platforms: [windows]
      
      
     
  themes:
    cmds:
      - nu table --list | each {|r| print ($r); print (ls | first 3 | table --theme $r)}
