# yaml-language-server: $schema=https://taskfile.dev/schema.json

# compose

version: '3'

vars:
  COMPOSE_GREETING: Hello, from COMPOSE !

tasks:
  default:
    cmds:
      - echo "{{.COMPOSE_GREETING}}"
    silent: true