# yaml-language-server: $schema=https://taskfile.dev/schema.json

# cloudflare

version: '3'

vars:
  CLOUDFLARE_GREETING: Hello, from CLOUDFLARE !

tasks:
  default:
    desc: cloudflare print
    cmds:
      - echo "{{.CLOUDFLARE_GREETING}}"
    silent: true