# yaml-language-server: $schema=https://taskfile.dev/schema.json

# caddy

version: '3'

vars:
  THIS_SRC_NAME: dns
  THIS_GREETING: Hello, from DNS !


tasks:
  default:
    desc: print
    cmds:
      - echo '{{.THIS_GREETING}}'
    silent: true
  dep:
    desc: dep
    cmds:
    silent: true
  bin:
    desc: build
    cmds:
      - task go:bin -- '{{.THIS_SRC_NAME}}'
    silent: true
  