# yaml-language-server: $schema=https://taskfile.dev/schema.json

# process_compose.taskfile.yml

version: '3'

env:
  
vars:
  ### bin
  PC_BIN_NAME: mod-process-compose
  # https://github.com/F1bonacc1/process-compose/releases/tag/v1.46.0
  # https://github.com/F1bonacc1/process-compose/releases/tag/v1.63.0
  PC_BIN_VERSION: v1.63.0
  PC_BIN_WHICH: 
    #sh: 'which {{.PC_BIN_NAME}}'
  PC_BIN_WHICH_VERSION:
    # Its too many lines.
    # My Issue: https://github.com/F1bonacc1/process-compose/issues/330
    #sh: '{{.PC_BIN_NAME}} version'
  
  # https://github.com/F1bonacc1/process-compose/releases/download/v1.46.0/process-compose_darwin_arm64.tar.gz
  # TODO: adapt to each OS.
  PC_BIN_URL_COMPRESS_NAME: process-compose_darwin_arm64.tar.gz
  PC_BIN_URL_EXTRACT_NAME: process-compose
  PC_BIN_URL: https://github.com/F1bonacc1/process-compose/releases/download/{{.PC_BIN_VERSION}}/{{.PC_BIN_URL_COMPRESS_NAME}}

  # --config stringArray      path to config files to load (env: PC_CONFIG_FILES)
  PC_VAR_CONFIG_NAME: 'pc-run.yaml'
  PC_VAR_CONFIG_PATH: '{{.USER_WORKING_DIR}}'
  PC_VAR_CONFIG_WHICH: '{{.PC_VAR_CONFIG_PATH}}/{{.PC_VAR_CONFIG_NAME}}'

  PC_CMD: '{{.PC_BIN_NAME}} --config {{.PC_VAR_CONFIG_WHICH}}'

tasks:
  default:
    desc: print
    cmds:
      - echo ''
      - echo '- bin'
      - echo 'PC_BIN_NAME:'                 {{.PC_BIN_NAME}}
      - echo 'PC_BIN_VERSION:'              {{.PC_BIN_VERSION}}
      - echo 'PC_BIN_WHICH:'                {{.PC_BIN_WHICH}}
      - 'which {{.PC_BIN_NAME}}'
      - echo 'PC_BIN_WHICH_VERSION:'        {{.PC_BIN_WHICH_VERSION}}
      - echo ''
      - echo '- bin url'
      - echo 'PC_BIN_URL_COMPRESS_NAME:'    {{.PC_BIN_URL_COMPRESS_NAME}}
      - echo 'PC_BIN_URL:'                  {{.PC_BIN_URL}}
      - echo ''
      - echo '- vars:'
      - echo 'PC_VAR_CONFIG_NAME:'          {{.PC_VAR_CONFIG_NAME}}
      - echo 'PC_VAR_CONFIG_PATH:'          {{.PC_VAR_CONFIG_PATH}}
      - echo 'PC_VAR_CONFIG_WHICH:'         {{.PC_VAR_CONFIG_WHICH}}
      - echo ''
      - echo '- cmd:'
      - echo 'PC_CMD:'                      {{.PC_CMD}}
      - echo ''
    silent: true

  dep:
    cmds:
      #- brew install f1bonacc1/tap/process-compose
      # OR
      # works !
      # todo; add check if binary exist in .DEP_PATH, if else. 
      # pull to .tmp
      - task base:shell-wgot-totmp -- {{.PC_BIN_URL}}
      # extract to .tmp
      - task base:shell-arc-extract-totmp -- {{.PC_BIN_URL_COMPRESS_NAME}}
      # copy files we want to .DEP
      - mv {{.BASE_TMP_PATH}}/{{.PC_BIN_URL_EXTRACT_NAME}} {{.BASE_DEP_PATH}}/{{.PC_BIN_NAME}}
      - rm -rf {{.BASE_TMP_PATH}}
     
    silent: false
  dep:del:
    cmds:
      - rm -f {{.BASE_DEP_PATH}}/{{.PC_BIN_NAME}}
      - ls -al {{.BASE_DEP_PATH}}
    silent: false
  dep:which:
    cmds:
      - task base:shell-which -- {{.PC_BIN_NAME}}
    silent: false

  
### run

  run:
    cmds:
      - '{{.PC_BIN_NAME}} -h'
    silent: false
  version:
    cmds:
      - '{{.PC_BIN_NAME}} version --short'
    silent: false
  up:
    cmds:
      - '{{.PC_CMD}} up'
    silent: false
  down:
    cmds:
      - '{{.PC_BIN_NAME}} down'
    silent: false
  list:
    cmds:
      - '{{.PC_BIN_NAME}} list'
    silent: false


