# yaml-language-server: $schema=https://taskfile.dev/schema.json

# taskfile.yml

version: '3'

# MUST have this ONLY in root for env variables to work.
#dotenv: ['.env', 'all.env', '{{.ENV}}/.env', '{{.HOME}}/.env']
dotenv: ['.env', 'all.env']

includes:
  local: 
    taskfile: ././../../remote-taskfile.yml
    flatten: true
  #remote: 
  #  taskfile: https://raw.githubusercontent.com/joeblew999/pb-stack/refs/heads/main/remote-taskfile.yml
  #  flatten: true

  #remote:
  #   https://github.com/saydulaev/taskfile
  #   taskfile: https://raw.githubusercontent.com/saydulaev/taskfile/v1.4.3/Taskfile.yml
  #   flatten: true

vars:
  #GO_VAR_BIN_FLAG_PRE: 'CGO_ENABLED=1'
  #GO_VAR_BIN_FLAG_POST: '-tags production -ldflags="-X"'

tasks:
  default:
    desc: Welcome. 
    cmds:
      - echo ''
      - '{{.BASE_TASK_CMD}} --list-all --yes --sort none'
    silent: false

  this:
    desc: build all explicitly.
    cmds:
      - '{{.BASE_TASK_CMD}} go:mod-tidy'
      - '{{.BASE_TASK_CMD}} bin:debug'

  bin:debug:
    desc: build all explicitly.
    cmds:
      - echo ''
      - echo 'Building all ...'

      # bin
      - '{{.BASE_TASK_CMD}} go:bin'
      - '{{.BASE_TASK_CMD}} go:inspect'
      
      # run
      - '{{.BASE_TASK_CMD}} go:run'
    silent: false

  bin:release:
    desc: build all explicitly.
    cmds:
      - echo ''
      - echo 'Building all ...'

      # bin
      - '{{.BASE_TASK_CMD}} go:garble'
      - '{{.BASE_TASK_CMD}} go:inspect'

      # run
      - '{{.BASE_TASK_CMD}} go:run'
    silent: false
