# https://taskfile.dev

version: '3'

includes:
  cogent:
    taskfile: ./../cogent.taskfile.yml
    flatten: true

vars:
  GREETING: Hello, World!

tasks:
  
  backend:
    dir: backend
    cmds:
      - go mod tidy
      - go run .

  frontend:
    dir: frontend
    cmds:
      - go mod tidy
      - go run .


