# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['dev.env', '{{.ENV}}/.env', '{{.HOME}}/.env']


includes:
  local: 
    taskfile: ./../../../dev-taskfile.yml
    flatten: true

tasks:
  all:
    cmds:
      - task src
      - task go:bin

  src:
    cmds:
      - task git:clone:src:del
      - task git:clone:src
  run:
    cmds:
      - task go:run

  
      