# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  KAMAL_GREETING: Hello, from KAMAL !

tasks:
  default:
    cmds:
      - echo "{{.KAMAL_GREETING}}"
    silent: true