# yaml-language-server: $schema=https://taskfile.dev/schema.json

# todo

version: '3'


# MUST have this ONLY in root for env variables to work.
dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  remote:
    taskfile: https://raw.githubusercontent.com/joeblew999/pb-stack/refs/heads/main/taskfile.yml
                
  remote:
    taskfile: https://raw.githubusercontent.com/saydulaev/taskfile/refs/heads/main/Taskfile.yml
    #taskfile: https://raw.githubusercontent.com/saydulaev/taskfile/v1.4.3/Taskfile.yml


vars:
  BASE_SRC_NAME: todo-with-task-includes
  TODO_GREETING: Hello, from todo project !
 
tasks:
  default:
    desc: todo print
    cmds:
      - echo "{{.TODO_GREETING}}"
    silent: true
  bin:
    cmds:
      - task go:bin
  run:
    cmds:
      - task go:run