# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  # Pick if you want local or remote task file loading.
  #local: 
  #  taskfile: ./../../remote-taskfile.yml
  #  flatten: true
  remote: 
    taskfile: https://raw.githubusercontent.com/joeblew999/pb-stack/refs/heads/main/remote-taskfile.yml
    flatten: true
                
vars:
  # MUST have this to work. Maybe can discover it later in base.
  BASE_SRC_NAME: todo-with-task-remote
 
tasks:
  default:
    cmds:
      - task base
      - task base:bin
      - task go:bin
 