# https://taskfile.dev

version: '3'

vars:
  # https://github.com/pocketbase/pocketbase
  PB_BIN_NAME: pb
  # https://github.com/pocketbase/pocketbase/releases/tag/v0.26.6
  PB_BIN_VERSION: v0.26.6


  # https://github.com/Snonky/pocketbase-gogen
  PB_GEN_BIN_NAME: pocketbase-gogen
  # https://github.com/Snonky/pocketbase-gogen/releases/tag/v0.6.1
  PB_GEN_BIN_VERSION: v0.6.1

tasks:
  default:
    cmds:
      - echo ""
      - echo "PB_BIN_NAME:"           {{.PB_BIN_NAME}}
      - echo "PB_BIN_VERSION:"        {{.PB_BIN_VERSION}}

      - echo "PB_GEN_BIN_NAME:"       {{.PB_GEN_BIN_NAME}}
      - echo "PB_GEN_BIN_VERSION:"    {{.PB_GEN_BIN_VERSION}}
      - echo ""
    silent: true

  dep-pb:
    desc: install pb
    cmds:
      - '{{.GO_BIN_NAME}} install github.com/pocketbase/pocketbase/examples/base@{{.PB_BIN_VERSION}}'
  dep-pb-gen:
    desc: install pb gen
    cmds:
      - '{{.GO_BIN_NAME}} install github.com/Snonky/pocketbase-gogen@@{{.PB_GEN_BIN_VERSION}}'