# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['dev.env', '{{.ENV}}/.env', '{{.HOME}}/.env']


includes:
  dev: 
    taskfile: ./../../dev-taskfile.yml
    flatten: true

tasks:
  all:
    cmds:
      - cd ajstarks__deck && task all
      - cd ajstarks__decksh && task all
      - cd ajstarks__ebcanvas && task all
  clean:
      cmds:
      # Need a way to remove src and .bin folders.
      #- cd ajstarks__deck && task go:clean
      #- cd ajstarks__decksh && task all
      #- cd ajstarks__ebcanvas && task all
