# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list-all
      - echo "{{.GREETING}}"
      -
    silent: true

### docker: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

  dep:
    cmds:
      # install wrangler

      # install tofu
      
      
  