# yaml-language-server: $schema=https://taskfile.dev/schema.json

# taskfile.yml

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['.env', 'all.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  dev: 
    taskfile: ./../../../../dev-taskfile.yml
    flatten: true
  cloudflare: 
    taskfile: ./../../cloudflare.taskfile.yml
  #  flatten: true


vars:
  GIT_VAR_ROOT_REPO_NAME: 'workers'
  GIT_VAR_SRC_REPO_URL: 'https://github.com/syumai/workers'

  THIS_SRC: '{{.GIT_VAR_ROOT_REPO_NAME}}/_examples/r2-image-server'

tasks:
  default:
    desc: Welcome. 
    cmds:
      - '{{.BASE_TASK_CMD}} --list-all --yes --sort none'
      - echo 'THIS_SRC:'      {{.THIS_SRC}}
      - echo 'THIS_SRC:'      {{.THIS_SRC}}

    silent: false
  src:
    cmds:
      - '{{.BASE_TASK_CMD}} git:clone:src'
  src:del:
    cmds:
      - '{{.BASE_TASK_CMD}} git:clone:src:del'
  bin:
    cmds:
      # TODO: Get Bun installed and working using task, not "brew install bun"
      - cd {{.THIS_SRC}} && bun install wrangler

      - cd {{.THIS_SRC}} && go run ../../cmd/workers-assets-gen
      # TODO: Get tinygo installed and working using task, not "brew install tinygo"
      - cd {{.THIS_SRC}} && tinygo build -o ./build/app.wasm -target wasm -no-debug ./...
  run:
    cmds:
      - cd {{.THIS_SRC}} && bunx wrangler dev
  deploy:
    cmds:
      # ERROR:  R2 bucket 'r2-image-viewer' not found. Please use a different name and try again. [code: 10085]
      # Need TOFU to setup the bucket first ?
      - cd {{.THIS_SRC}} && bunx wrangler deploy