# yaml-language-server: $schema=https://taskfile.dev/schema.json

# taskfile.yml

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['.env', 'all.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  local: 
    taskfile: ./../../../dev-taskfile.yml
    flatten: true

vars:
  GIT_VAR_SRC_REPO_URL: 'https://github.com/naveenrajm7/packer-plugin-utm'
  GIT_VAR_SRC_REPO_NAME: 'packer-plugin-utm'
  

  #THIS_SRC_PATH: '{{.BASE_SRC_PATH}}/{{.GIT_VAR_ROOT_REPO_NAME}}'
  #THIS_SRC_PATH: '{{joinPath .BASE_SRC_PATH .GIT_VAR_ROOT_REPO_NAME }}' 

tasks:
  default:
    desc: Welcome. 
    cmds:
      - '{{.BASE_TASK_CMD}} --list-all --yes --sort none'

      - echo 'GIT_VAR_ROOT_REPO_NAME:'      {{.GIT_VAR_SRC_REPO_NAME}}
      - echo 'GIT_VAR_SRC_REPO_URL:'        {{.GIT_VAR_SRC_REPO_URL}}
      - echo 'THIS_SRC_PATH:'     {{.THIS_SRC_PATH}}

    silent: false
  src:
    cmds:
      - '{{.BASE_TASK_CMD}} git:clone:src'
  src:del:
    cmds:
      - '{{.BASE_TASK_CMD}} git:clone:src:del'
  bin:
    cmds:
      - echo > go.work && go work use {{.THIS_SRC_PATH}}
      - '{{.BASE_TASK_CMD}} go:bin'
  run:
    cmds:
      - cd {{.THIS_SRC_PATH}} && 
  deploy:
    cmds:
      - cd {{.THIS_SRC_PATH}} && 