# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['dev.env', '{{.ENV}}/.env', '{{.HOME}}/.env']


includes:
  dev: 
    taskfile: ./../../../dev-taskfile.yml
    flatten: true

vars:
  DECKSH_BIN_ENTRY: './cmd/decksh'
  DECKSH_BIN_NAME: 'decksh'

  DECKFMT_BIN_ENTRY: './cmd/dshfmt'
  DECKFMT_BIN_NAME: 'dshfmt'

  DECKLINT_BIN_ENTRY: './cmd/dshlint'
  DECKLINT_BIN_NAME: 'dshlint'

tasks:

  all:
    cmds:
      - task src
      - task bin
  src:
    cmds:
      #- task git:clone:src:check
      - task git:clone:src:del
      - task git:clone:src
      
  bin:
    cmds:
      - task go:mod:work
      - task go:mod:tidy
      - task go:bin:native

      - task GO_VAR_BIN_ENTRY_PATH='{{.DECKSH_BIN_ENTRY}}' GO_VAR_BIN_NAME='{{.DECKSH_BIN_NAME}}' go:bin:native
      - task GO_VAR_BIN_ENTRY_PATH='{{.DECKFMT_BIN_ENTRY}}' GO_VAR_BIN_NAME='{{.DECKFMT_BIN_NAME}}' go:bin:native
      - task GO_VAR_BIN_ENTRY_PATH='{{.DECKLINT_BIN_ENTRY}}' GO_VAR_BIN_NAME='{{.DECKLINT_BIN_NAME}}' go:bin:native

      - task GO_VAR_BIN_ENTRY_PATH='{{.DECKSH_BIN_ENTRY}}' GO_VAR_BIN_NAME='{{.DECKSH_BIN_NAME}}' go:bin:wasm
      - task GO_VAR_BIN_ENTRY_PATH='{{.DECKFMT_BIN_ENTRY}}' GO_VAR_BIN_NAME='{{.DECKFMT_BIN_NAME}}' go:bin:wasm
      - task GO_VAR_BIN_ENTRY_PATH='{{.DECKLINT_BIN_ENTRY}}' GO_VAR_BIN_NAME='{{.DECKLINT_BIN_NAME}}' go:bin:wasm

  run:
    cmds:
      - task go:run:native -- -h

 