# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['run.env', '{{.ENV}}/.env', '{{.HOME}}/.env']


env:
  # this allow overriding from CLI.
  HTML_DEEP_NAME: '{{.HTML_DEEP_NAME | default "override-taskenv.html" }}'

vars:
  HTML_DEEP_PATH: '{{.HTML_DEEP_PATH | default "{{.USER_WORKING_DIR}}" }}'
  HTML_DEEP_WHICH: '{{.HTML_DEEP_PATH}}/{{.HTML_DEEP_NAME}}'
  HTML_DEEP_WHICH_JOIN: '{{joinPath .HTML_DEEP_PATH .HTML_DEEP_NAME}}'

tasks:
  default:
    cmds:
      - echo ''
      - echo 'HTML_DEEP_PATH              {{shellQuote .HTML_DEEP_PATH}}'
      - echo 'HTML_DEEP_NAME              {{.HTML_DEEP_NAME}}'
      - echo ''
      - echo 'HTML_DEEP_WHICH             {{shellQuote .HTML_DEEP_WHICH}}'
      - echo 'HTML_DEEP_WHICH_JOIN        {{shellQuote .HTML_DEEP_WHICH_JOIN}}'
      - echo ''
    silent: true
  override-01:
    cmds:
      - HTML_DEEP_NAME=01 task
  override-02:
    cmds:
      # fails, but works from termianl shell using ./run.sh
      - ./run.sh

  