# .task-experiments.yml
# If .env and .task-experiments.yml are present the values in the .task-experiments.yml file take precedence.

experiments:
  
  # https://taskfile.dev/experiments/env-precedence
  ENV_PRECEDENCE: 1

  # https://taskfile.dev/experiments/gentle-force/
  GENTLE_FORCE: 1

  # https://taskfile.dev/experiments/map-variables/?proposal=2
  MAP_VARIABLES: 2

  # https://taskfile.dev/experiments/remote-taskfiles/
  REMOTE_TASKFILES: 1