# yaml-language-server: $schema=https://taskfile.dev/schema.json

# taskfile.yml

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['.env', 'all.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  dev: 
    taskfile: ./../../../../dev-taskfile.yml
    flatten: true
  cloudflare: 
    taskfile: ./../../cloudflare.taskfile.yml
  #  flatten: true


vars:

tasks:
  default:
    desc: default
    cmds:
      - '{{.BASE_TASK_CMD}} --list-all --yes --sort none'
    silent: false
  