# https://taskfile.dev

# caddy

version: '3'

vars:
  BASE_SRC_NAME: caddy
  CADDY_GREETING: Hello, from CADDY !


tasks:
  default:
    desc: caddy print
    cmds:
      - echo "{{.CADDY_GREETING}}"
    silent: true
  dep:
    desc: caddy install
    cmds:
      - echo "{{.CADDY_GREETING}}"
    silent: true
  bin:
    desc: caddy build
    cmds:
      - task go:bin
    silent: true
  