# yaml-language-server: $schema=https://taskfile.dev/schema.json

# caddy

version: '3'

vars:
  THIS_SRC_NAME: caddy
  THIS_GREETING: Hello, from CADDY !

tasks:
  default:
    desc: caddy print
    cmds:
      - echo '{{.THIS_GREETING}}'
    silent: true
  dep:
    desc: caddy install
    cmds:
      - echo '{{.THIS_GREETING}}'
    silent: true
  bin:
    desc: caddy build
    cmds:
      - task go:bin -- '{{.THIS_SRC_NAME}}'
    silent: true
  