# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  MINIO_GREETING: Hello, from MINIO !

tasks:
  default:
    cmds:
      - echo "{{.MINIO_GREETING}}"
    silent: true