# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  process-compose-remote:
    taskfile: https://raw.githubusercontent.com/joeblew999/pb-stack/refs/heads/main/mod/process-compose/process-compose.taskfile.yml
    flatten: true
