# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  clone:
    cmds:
      - git clone https://github.com/starfederation/datastar
      - echo datastar >> .gitignore
  