server:
  address: "0.0.0.0:32010"
  max_connections: 10

database:
  dsn: "duckdb://:memory:"
  max_open_conns: 32
  health_check_period: "30s"

logging:
  level: "info"
  format: "json"

metrics:
  enabled: true
  endpoint: ":9090"

tracing:
  enabled: false

auth:
  enabled: true
  type: oauth2
  oauth2_auth:
    client_id: "your-client-id"
    client_secret: "your-client-secret"
    redirect_url: "localhost:8080" # OAuth2 HTTP server address
    authorize_endpoint: "/oauth2/authorize"
    token_endpoint: "/oauth2/token"
    scopes: ["read", "write"]
    access_token_ttl: 1h
    refresh_token_ttl: 24h
    allowed_grant_types:
      ["authorization_code", "refresh_token", "client_credentials"]