# ci

name: ci
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}
        id: go

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: task base
        run: task base --yes
          
      - name: task git
        run: task git

      - name: task go
        run: task go