# ci

name: ci
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.24.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # https://github.com/actions/setup-go
      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v5
        with:
          go-version: '${{matrix.go-version}}'

      # https://github.com/arduino/setup-task
      # TODO: Get TASK version from .env, so it single sourced.
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: '3.42.1'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Check it can see all remotes...
      - name: task 
        run: task --list-all --yes --verbose

      - name: task base
        run: task base --verbose
          
      - name: task git
        run: task git --verbose

      - name: task go
        run: task go --verbose